package app.uni.programacion;

import app.uni.controllers.CalculateController;
import app.uni.controllers.MoneyController;
import app.uni.controllers.TempController;
import app.uni.panels.PnlCalculator;
import app.uni.panels.PnlMoney;
import app.uni.panels.PnlTemp;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author iGeorge
 */
public class FrmApp extends javax.swing.JFrame {
    private CalculateController calculateController;
    private PnlCalculator pnlCalculate;
    private PnlTemp pnlTemp;
    private TempController tempController;
    private PnlMoney pnlMoney;
    private MoneyController moneyController;
    

    public JButton getBtnCalc() {
        return btnCalc;
    }

    public void setBtnCalc(JButton btnCalc) {
        this.btnCalc = btnCalc;
    }

    public JButton getBtnMoney() {
        return btnMoney;
    }

    public void setBtnMoney(JButton btnMoney) {
        this.btnMoney = btnMoney;
    }

    

    public JButton getBtnTemp() {
        return btnTemp;
    }

    public void setBtnTemp(JButton btnTemp) {
        this.btnTemp = btnTemp;
    }
    
    
    
    /**
     * Creates new form FrmApp
     */
    public FrmApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCalc = new javax.swing.JButton();
        btnTemp = new javax.swing.JButton();
        btnMoney = new javax.swing.JButton();
        panelito = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(3, 0));

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        btnCalc.setText("Calculadora");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalc);

        btnTemp.setText("Temp");
        btnTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempActionPerformed(evt);
            }
        });
        jPanel1.add(btnTemp);

        btnMoney.setText("Moneda");
        btnMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoneyActionPerformed(evt);
            }
        });
        jPanel1.add(btnMoney);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        panelito.setBackground(new java.awt.Color(255, 255, 255));
        panelito.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelito, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        if(pnlCalculate == null){
            pnlCalculate = new PnlCalculator();
            calculateController = new CalculateController(pnlCalculate);
        }
        
        if(panelito.getComponentCount() > 0){
            panelito.remove(0);
        }
        
        panelito.add(pnlCalculate, BorderLayout.CENTER);
        validate();
    }//GEN-LAST:event_btnCalcActionPerformed

    private void btnTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempActionPerformed
        // TODO add your handling code here:
        if(pnlTemp == null){
            pnlTemp = new PnlTemp();
            tempController = new TempController(pnlTemp);
        }
        
        if(panelito.getComponentCount() > 0){
            panelito.remove(0);
        }
        
        panelito.add(pnlTemp, BorderLayout.CENTER);
        validate();
    }//GEN-LAST:event_btnTempActionPerformed

    private void btnMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoneyActionPerformed
        // TODO add your handling code here:
        if(pnlMoney == null){
            pnlMoney = new PnlMoney();
            moneyController = new MoneyController(pnlMoney);
        }
        
        if(panelito.getComponentCount() > 0){
            panelito.remove(0);
        }
        
        panelito.add(pnlMoney, BorderLayout.CENTER);
        validate();
        
    }//GEN-LAST:event_btnMoneyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnMoney;
    private javax.swing.JButton btnTemp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelito;
    // End of variables declaration//GEN-END:variables
}
